server/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.core.validators import MinValueValidator, MaxValueValidator

import matplotlib.pyplot as plt
import numpy as np
from math import pi
from matplotlib.backends.backend_agg import FigureCanvasAgg as FigureCanvas
from matplotlib.figure import Figure
from matplotlib.dates import DateFormatter
import os

class Skill(models.Model):
	'''model for skill'''
	name = models.CharField(max_length=500)


class Tag(models.Model):
	'''model for hackathon tags '''
	tagname = models.CharField(max_length=30, default="[Undefinded]")
	def __str__(self):
		return self.tagname


class Profile(models.Model):
	'''model for Profile'''
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	avatar = models.ImageField(upload_to='uploads/', default = 'unknown_img.jpg')
	access_level = models.IntegerField(
		default=0, verbose_name='Уровень доступа')
	birthday = models.DateField(auto_now=True)
	name = models.CharField(max_length=100)
	surname = models.CharField(max_length=100)
	github = models.CharField(max_length=100)
	facebook = models.CharField(max_length=100)
	vk = models.CharField(max_length=100)
	skills = models.ManyToManyField(Skill)


class Hackathon(models.Model):
	'''model for hackathon'''
	name = models.CharField(max_length=300)
	description = models.CharField(max_length=5000, default="")
	date = models.DateField()
	users = models.ManyToManyField(User)
	duration = models.IntegerField(validators=[MinValueValidator(1), ])
	max_members = models.IntegerField(validators=[MinValueValidator(1), ])
	tags = models.ManyToManyField(Tag, related_name="tags", verbose_name='Теги')

	@property
	def hack_url(self):
		return "/hack_info/{0}".format(self.id)


class News(models.Model):
	'''class for announcement'''
	text = models.CharField(max_length=2000)


class Invintation(models.Model):
	'''class for invitation to the hackthone'''
	from_Profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='from_Profile')
	to_Profile = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='to_Profile')
	hackathon = models.ForeignKey(Hackathon, on_delete=models.CASCADE, related_name='hackathon')
	date = models.DateField(auto_now=True)


class Team(models.Model):
	'''class for team'''
	name = models.CharField(max_length=100)
	users = models.ManyToManyField(User)
	hackathones = models.ManyToManyField(Hackathon)

class UserRating(models.Model):
	frontend = models.FloatField()
	backend = models.FloatField()
	ml = models.FloatField()
	management = models.FloatField()
	design = models.FloatField()
	ar = models.FloatField()
	blockchain = models.FloatField()
	user = models.OneToOneField(Profile, on_delete=models.CASCADE)
	android = models.FloatField()
	ios = models.FloatField()
	d2 = models.FloatField()
	d3 = models.FloatField()

	@property
	def diagram(self):
		fig = plt.Figure()
		labels = ['frontend', 'backend', 'management', 'blockchain']
		values = [self.user.userrating.frontend, self.user.userrating.backend, self.user.userrating.management,
				  self.user.userrating.blockchain]
		N = len(labels)

		x_as = [n / float(N) * 2 * pi for n in range(N)]
		values += values[:1]
		x_as += x_as[:1]
		plt.rc('axes', linewidth=0.5, edgecolor="#888888")

		# Create polar plot
		ax = plt.subplot(111, polar=True)
		# Set clockwise rotation. That is:
		ax.set_theta_offset(pi / 2)
		ax.set_theta_direction(-1)

		# Set position of y-labels
		ax.set_rlabel_position(0)

		# Set color and linestyle of grid
		ax.xaxis.grid(True, color="#888888", linestyle='solid', linewidth=0.5)
		ax.yaxis.grid(True, color="#888888", linestyle='solid', linewidth=0.5)
		# Set number of radial axes and remove labels
		plt.xticks(x_as[:-1], [])

		plt.yticks([20, 40, 60, 80, 100], ["20", "40", "60", "80", "100"])

		# Plot data
		ax.plot(x_as, values, linewidth=0, linestyle='solid', zorder=3)

		# Fill area
		ax.fill(x_as, values, 'b', alpha=0.3)

		# Set axes limits
		plt.ylim(0, 100)

		# Draw ytick labels to make sure they fit properly
		for i in range(N):
			angle_rad = i / float(N) * 2 * pi

			if angle_rad == 0:
				ha, distance_ax = "center", 10
			elif 0 < angle_rad < pi:
				ha, distance_ax = "left", 1
			elif angle_rad == pi:
				ha, distance_ax = "center", 1
			else:
				ha, distance_ax = "right", 1

			ax.text(angle_rad, 100 + distance_ax, labels[i], size=10, horizontalalignment=ha,
					verticalalignment="center")
		url = 'media/dia'+ str(self.user.id) + '.jpg'
		plt.savefig(url)
		return url


class Achievement(models.Model):
	'''class fot achievement'''
	user = models.ManyToManyField(Profile)
	receiving_date = models.DateTimeField()
	image = models.ImageField()
	info = models.CharField(max_length=1000)


class HackRateByUser(models.Model):
	'''model for rates by User'''
	user = models.ForeignKey(Profile, on_delete=models.CASCADE)
	hack = models.ForeignKey(Hackathon, on_delete=models.CASCADE)
	rate = models.IntegerField(validators=[MinValueValidator(1), MaxValueValidator(5)])
	comment = models.CharField(max_length=1000)

server/templates/hack_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{{ hack.name }}</title>
</head>
<body>
<div>
    <h1>{{ hack.name }}</h1>
    <p>{{ hack.description }}</p>
    <p>{{ hack.date }}</p>
    <p><i>Rating: </i>
        {% if rating != -1 %}
            {{ rating }}
        {% else %}
            Nothing
        {% endif %}
    </p>
    {% if not is_user_applied %}
    <input type="submit" value="Apply"
        onclick="window.location='{% url 'add_user_to_hack' hack.id user_id %}';" />
    {% elif user_has_team %}
        <p>You are applied! And you are at team {{ users_team_in_hack.name }}</p>
        {% if not has_rate %}
            <input type="button" value="review" onclick="reviewShowOnClick()">
        {% endif %}
    {% else %}
        <input type="submit" value="Create team"
        onclick="window.location='{% url 'create_team' hack.id %}';" />
    {% endif %}

    {% if  has_rate %}
        <p><b>You rate: </b> {{ rate.rate }}</p>
        <p><b>You comment: </b>{{ rate.comment }}</p>
    {% else %}
    <div style="visibility: hidden" id="review">

        <form method="post">
            {% csrf_token %}

            {% if can_review %}
            {% for field in review_form %}
                <p>{{ field.label_tag }} {{field}} </p>
            {% endfor %}
                <input type="submit" value="Comment"/>
            {% else %}
                 <p style="color: red">You're can't vote!</p>
            {% endif %}
        </form>
    </div>

    <script>
        function reviewShowOnClick() {
            document.getElementById("review").style.visibility = "visible";
            //alert("kek!");
        }
    </script>
    {% endif %}
</div>
</body>
</html>

server/templates/hackaton_list.html
<!doctype html>
<html>
<head>
    {% load static %}
	<meta charset="UTF-8">
	<title>In.Team - Хакатоны</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<script src="https://cdn.jsdelivr.net/npm/vue"></script>
	<link href="{% static 'css/bootstrap.css' %} " rel="stylesheet">
	<link href="{% static 'css/board.css' %}" rel="stylesheet">
</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-height">
		<a class="navbar-brand center logo" href="#">In.Team</a>
		<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
			<span class="navbar-toggler-icon"></span>
		</button>

		<div class="collapse navbar-collapse" id="navbar1">
			<ul class="navbar-nav mr-auto">
				<li class="nav-item active">
					<a class="nav-link navbar-fontSize" href="#">Хакатоны<span class="sr-only">(current)</span></a>
				</li>
				<li class="nav-item" style="padding-left: 5%">
					<a class="nav-link navbar-fontSize" href="#">Хакеры</a>
				</li>
			</ul>
			<div>
                <p id="userName" class="lable-userName"><a href="{% url 'profile' %}">{{ user.name }} {{ user.surname }}</a></p>
				<img src="/media/{{ user.avatar }}" id="user_avatar" class="avatar" alt="">
			</div>
		</div>
	</nav>
	<div>
        {% if hacks %}
            {% for hack in hacks %}
                <div class="hackathone-broad">
			        <img class="hackathone-avatar" id="hackathone_avatar" alt="">
			        <div style="display: inline-block">
				        <div class="hackathone-text">
					        <h class="center">{{ hack.name }}</h>
					        <p>{{hack.description}}</p>
				        </div>
                        <a href="{% url 'hack_info' hack.id %}" class="hackathone-moreInfo">Подробнее</a>
			        </div>
		        </div>
            {% endfor %}
        {% else %}
            Хакатонов нет
        {% endif %}
	</div>
</body>
</html>

server/templates/profile.html
<!doctype html>
<html>
	<head>
		<meta charset="UTF-8">
        {% load static %}
		<title>In.Team - Профиль</title>
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<script src="https://cdn.jsdelivr.net/npm/vue"></script>
		<link href="{% static 'css/bootstrap.css' %}" rel="stylesheet">
		<link href="{% static 'css/person.css' %}" rel="stylesheet">
		<link href="{% static 'css/design.css' %}" rel="stylesheet">
	</head>

	<body>
		<nav class="navbar navbar-expand-lg navbar-dark bg-dark navbar-height">
			<a class="navbar-brand center logo" href="#">In.Team</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1" aria-controls="navbar1" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbar1">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<a class="nav-link navbar-fontSize" href="{% url 'hack_list' %}">Хакатоны<span class="sr-only">(current)</span></a>
					</li>
					<li class="nav-item" style="padding-left: 5%">
						<a class="nav-link navbar-fontSize" href="#">Хакеры</a>
					</li>
					<li class="nav-item" style="padding-left: 5%">
						<a class="nav-link navbar-fontSize" href="#">Команды</a>
					</li>
				</ul>
			</div>
		</nav>
		<div class="board">
			<table width="300px" cellspacing="0" cellpadding="5">
				<tr>
					<td width="100%" valign="top">
						<div class="leftBoard">
							<div class="avatar ds-broad">
								<img src="/media/{{user.avatar}}" class="avatar" alt="">
							</div>

							<div class="achievement ds-broad">
                            <ul class="list-group">
                                {% for achiev in user.achievement_set.all %}
                                    <li class="list-group-item">{{ achiev.info }}</li>
                                {% endfor %}
                            </ul>
							</div>

							<div class="friends ds-broad">

							</div>

							<div class="hackathones ds-broad">

							</div>
						</div>
					</td>
					<td width="100%" valign="top">
						<div class="rightBoard">
							<div class="userInfo ds-broad" style="padding-left: 4%">
                                <h1 style="padding-left: 30%">{{ user.name }} {{ user.surname }}</h1>
                                <h2 style="padding: 10%;">Skills</h2>
                                <ul class="list-group">
                                {% for skill in skills %}
                                    <li class="list-group-item">{{ skill.name }}</li>
                                {% endfor %}
                                </ul>
							</div>
                            <div class="levelInfo ds-broad">
                                {%  if chart %}
                                    <img src="/{{chart}}"/><br>
                                {%  endif %}
						    </div>

						</div>
					</td>
				</tr>
			</table>
		</div>
	</body>
</html>

server/templates/team_info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    
    {% load static %}
    <script src="{% static 'ajax_select/js/bootstrap.js' %}"></script>
<script src="{% static 'ajax_select/js/ajax_select.js' %}"></script>
<link rel="stylesheet" type="text/css" href="{% static 'ajax_select/css/ajax_select.css' %}">
    <title>Title</title>
</head>
<body>
    <p>{{ team.name }}</p>
    {% for user in users %}
        <tr>{{ user.username }}</tr> <br>
    {% endfor %}
<br>
    <form method="post">
            {% csrf_token %}
            {% for field in form %}
            {{ field.label_tag }}<br>
            {{field}}
            {% for error in field.errors %}
            <p style="color: red">{{ error }}</p>
          {% endfor %}
            {% endfor %}
            <button type="submit">Search</button>
    </form>
    {% if candidates %}
    <p>
        {% for can in candidates %}
            <form method="post" action="/add_user_to_team/{{team.id}}/{{can.user_id}}">
            {% csrf_token %}
            {{can.name}} {{can.surname}} <button type="submit">Добавить</button> <br>
        </form>
        {% endfor %}
    </p>
    {% endif %}
</body>
</html>